"""Compatibilidade legado para views do app Zabbix.

As views foram reorganizadas em m?dulos menores (`reports`, `inventory`,
`diagnostics`, `lookup`). Este arquivo reexporta os principais endpoints para
evitar que integra??es antigas que importavam `zabbix_api.views` quebrem.
"""

from .reports import (
    zabbix_all_hosts_performance,
    zabbix_all_latest_data,
    zabbix_clear_cache,
    zabbix_critical_problems,
    zabbix_events,
    zabbix_events_summary,
    zabbix_host_detail,
    zabbix_host_graphs,
    zabbix_host_items,
    zabbix_host_latest_data,
    zabbix_host_network_info,
    zabbix_host_performance,
    zabbix_host_problems,
    zabbix_host_triggers,
    zabbix_hostgroups,
    zabbix_hosts,
    zabbix_hosts_availability,
    zabbix_hosts_network_info,
    zabbix_item_history,
    zabbix_monitoring_overview,
    zabbix_problems,
    zabbix_problems_by_severity,
    zabbix_problems_summary,
    zabbix_recent_events,
    zabbix_status,
    zabbix_templates,
    zabbix_test,
)
from .inventory import (
    api_add_device_from_zabbix,
    api_bulk_create_inventory,
    api_cable_value_mapping_status,
    api_device_port_optical_status,
    api_device_ports,
    api_device_ports_with_optical,
    api_fiber_cables,
    api_fiber_detail,
    api_fiber_live_status,
    api_fibers_live_status_all,
    api_fibers_refresh_status,
    api_import_fiber_kml,
    api_port_traffic_history,
    api_sites,
    api_update_cable_oper_status,
    api_zabbix_discover_hosts,
    combine_cable_status,
    fetch_interface_status,
    import_kml_modal,
)
from .diagnostics import (
    api_test_ping,
    api_test_ping_telnet,
    api_test_telnet,
    test_set_cable_down,
    test_set_cable_unknown,
    test_set_cable_up,
)
from .lookup import (
    lookup_hosts,
    lookup_host_interfaces,
    lookup_interface_details,
)

__all__ = [
    # reports
    "zabbix_all_hosts_performance",
    "zabbix_all_latest_data",
    "zabbix_clear_cache",
    "zabbix_critical_problems",
    "zabbix_events",
    "zabbix_events_summary",
    "zabbix_host_detail",
    "zabbix_host_graphs",
    "zabbix_host_items",
    "zabbix_host_latest_data",
    "zabbix_host_network_info",
    "zabbix_host_performance",
    "zabbix_host_problems",
    "zabbix_host_triggers",
    "zabbix_hostgroups",
    "zabbix_hosts",
    "zabbix_hosts_availability",
    "zabbix_hosts_network_info",
    "zabbix_item_history",
    "zabbix_monitoring_overview",
    "zabbix_problems",
    "zabbix_problems_by_severity",
    "zabbix_problems_summary",
    "zabbix_recent_events",
    "zabbix_status",
    "zabbix_templates",
    "zabbix_test",
    # inventory
    "api_add_device_from_zabbix",
    "api_bulk_create_inventory",
    "api_cable_value_mapping_status",
    "api_device_port_optical_status",
    "api_device_ports",
    "api_device_ports_with_optical",
    "api_fiber_cables",
    "api_fiber_detail",
    "api_fiber_live_status",
    "api_fibers_live_status_all",
    "api_fibers_refresh_status",
    "api_import_fiber_kml",
    "api_port_traffic_history",
    "api_sites",
    "api_update_cable_oper_status",
    "api_zabbix_discover_hosts",
    "combine_cable_status",
    "fetch_interface_status",
    "import_kml_modal",
    # diagnostics
    "api_test_ping",
    "api_test_ping_telnet",
    "api_test_telnet",
    "test_set_cable_down",
    "test_set_cable_unknown",
    "test_set_cable_up",
    # lookup
    "lookup_hosts",
    "lookup_host_interfaces",
    "lookup_interface_details",
]

