# Generated by Django 5.2.7 on 2025-10-09 10:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('vendor', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('zabbix_hostid', models.CharField(blank=True, help_text='hostid no Zabbix', max_length=32)),
            ],
            options={
                'ordering': ['site__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FiberCable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('length_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('path_coordinates', models.JSONField(blank=True, help_text="Lista de pontos [{'lat': -16.6, 'lng': -49.2}, ...]", null=True)),
                ('status', models.CharField(choices=[('up', 'Operacional'), ('down', 'Indispon?vel'), ('degraded', 'Degradado'), ('unknown', 'Desconhecido')], default='unknown', max_length=15)),
                ('last_status_update', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FiberEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('previous_status', models.CharField(blank=True, max_length=15)),
                ('new_status', models.CharField(max_length=15)),
                ('detected_reason', models.CharField(blank=True, max_length=255)),
                ('fiber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='zabbix_api.fibercable')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('zabbix_item_key', models.CharField(blank=True, help_text='Chave item/interface no Zabbix (ex: net.if.in[ether10])', max_length=255)),
                ('zabbix_interfaceid', models.CharField(blank=True, help_text='interfaceid no Zabbix', max_length=32)),
                ('rx_power_item_key', models.CharField(blank=True, help_text='Item de pot?ncia ?ptica RX (ex: hwEntityOpticalLaneRxPower[ID])', max_length=255)),
                ('tx_power_item_key', models.CharField(blank=True, help_text='Item de pot?ncia ?ptica TX (ex: hwEntityOpticalLaneTxPower[ID])', max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='zabbix_api.device')),
            ],
            options={
                'ordering': ['device__site__name', 'device__name', 'name'],
                'unique_together': {('device', 'name')},
            },
        ),
        migrations.AddField(
            model_name='fibercable',
            name='destination_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiber_destination', to='zabbix_api.port'),
        ),
        migrations.AddField(
            model_name='fibercable',
            name='origin_port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiber_origin', to='zabbix_api.port'),
        ),
        migrations.AddField(
            model_name='device',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='zabbix_api.site'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('site', 'name')},
        ),
    ]
