# Generated by Django 5.2.7 on 2025-10-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='zabbix_itemid',
            field=models.CharField(blank=True, help_text='itemid no Zabbix', max_length=32),
        ),
    ]
