# Generated by Django 5.2.7 on 2025-10-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_api', '0002_port_zabbix_itemid'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_icon',
            field=models.ImageField(blank=True, null=True, upload_to='device_icons/'),
        ),
    ]
