# Generated by Django 5.2.7 on 2025-10-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_api', '0005_alter_device_device_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_icon',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/img/device_icons/'),
        ),
    ]
