# Generated by Django 5.2.7 on 2025-10-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_api', '0006_alter_device_device_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='zabbix_item_id_trafego_in',
            field=models.CharField(blank=True, help_text='itemid tr?fego entrada no Zabbix', max_length=32),
        ),
        migrations.AddField(
            model_name='port',
            name='zabbix_item_id_trafego_out',
            field=models.CharField(blank=True, help_text='itemid tr?fego sa?da no Zabbix', max_length=32),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_icon',
            field=models.ImageField(blank=True, null=True, upload_to='img/device_icons/'),
        ),
    ]
