# Generated by Django 5.2.7 on 2025-10-14 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_api', '0007_port_zabbix_item_id_trafego_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='cpu_usage_item_key',
            field=models.CharField(blank=True, help_text='Chave do item de uso de CPU no Zabbix (ex: system.cpu.util[,user])', max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='uptime_item_key',
            field=models.CharField(blank=True, help_text='Chave do item de uptime no Zabbix (ex: system.uptime)', max_length=255),
        ),
    ]
